### ISSUE TITLE
Glamorous innerRef prop should migrate to normal ref

### ISSUE THREAD

**Issue by slorber** [TejasQ/babel-plugin-glamorous-to-emotion#13]
Hi,

To get access to underlying glamorous dom node, we can use `innerRef`

`<glamorous.Div innerRef={...}>`

After the codemods run I get

`<div css={{innerRef: ...}}>`

I should rathet get

`<div ref={...}>`

**Comment by TejasQ** [comment]
@danielberndt up for it?

**Comment by danielberndt** [comment]
Yes, very good point. Should be a quick one. I'll send a PR in a bit :)
